package capability

import (
	"fmt"
	"strings"
)

// Render produces the generated capability reference (docs/reference/
// capabilities.md). It is a pure function of the registry, so the committed
// file can be checked for drift by regenerating it in a test.
func Render(caps []Capability) string {
	var b strings.Builder
	b.WriteString("<!-- Code generated by `go run ./tools/capdoc`. DO NOT EDIT. -->\n")
	b.WriteString("<!-- Source: internal/capability/registry.go. The parity test in cmd/mnemos holds it to the real transports. -->\n\n")
	b.WriteString("# Capability reference\n\n")
	b.WriteString("Every operation Mnemos exposes, and how each transport provides it. ")
	b.WriteString("A cell is either the operations that implement the capability or the reason the transport does not. ")
	b.WriteString("**GAP** marks an omission that is not a decision: an operation that should exist on that transport and does not yet.\n\n")
	b.WriteString("| Transport | Surface |\n|---|---|\n")
	b.WriteString("| go | the embedded library, `mnemos.Memory` |\n")
	b.WriteString("| rest | `mnemos serve` |\n")
	b.WriteString("| grpc | `mnemos.v1.MnemosService` |\n")
	b.WriteString("| mcp | `mnemos mcp` (stdio and `--http`) |\n")
	b.WriteString("| mcp-lite | the root `mcp` package, a core subset |\n")
	b.WriteString("| http-lite | the root `http` package, a core subset |\n")
	b.WriteString("| client | `go.klarlabs.de/mnemos/client` |\n\n")

	gaps := Gaps(caps)
	fmt.Fprintf(&b, "%d capabilities, %d acknowledged gaps.\n\n", len(caps), len(gaps))

	// Summary matrix: one row per capability, one column per transport.
	b.WriteString("| Capability | Effect |")
	for _, t := range Transports {
		fmt.Fprintf(&b, " %s |", t)
	}
	b.WriteString("\n|---|---|")
	for range Transports {
		b.WriteString(":-:|")
	}
	b.WriteString("\n")
	for _, c := range caps {
		fmt.Fprintf(&b, "| [`%s`](#%s) | %s |", c.ID, anchor(c.ID), c.Effect)
		for _, t := range Transports {
			bd := c.On[t]
			switch {
			case bd.Bound():
				b.WriteString(" ✓ |")
			case bd.IsGap():
				b.WriteString(" GAP |")
			default:
				b.WriteString(" — |")
			}
		}
		b.WriteString("\n")
	}

	b.WriteString("\n## Capabilities\n")
	for _, c := range caps {
		fmt.Fprintf(&b, "\n### %s\n\n%s (%s).\n\n", c.ID, c.Summary, c.Effect)
		b.WriteString("| Transport | Binding |\n|---|---|\n")
		for _, t := range Transports {
			bd := c.On[t]
			if bd.Bound() {
				ops := make([]string, len(bd.Ops))
				for i, op := range bd.Ops {
					ops[i] = "`" + op + "`"
				}
				fmt.Fprintf(&b, "| %s | %s |\n", t, strings.Join(ops, ", "))
			} else {
				reason := strings.ReplaceAll(bd.Reason, "|", "\\|")
				if bd.IsGap() {
					reason = "**GAP** —" + strings.TrimPrefix(reason, GapPrefix)
				} else {
					reason = "_" + reason + "_"
				}
				fmt.Fprintf(&b, "| %s | %s |\n", t, reason)
			}
		}
		if c.Notes != "" {
			fmt.Fprintf(&b, "\n> %s\n", c.Notes)
		}
	}
	return b.String()
}

// anchor is the Markdown heading anchor for an id: GitHub lowercases and drops
// "." from headings.
func anchor(id string) string {
	return strings.ReplaceAll(strings.ToLower(id), ".", "")
}
