package extract

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"testing"
	"time"

	"go.klarlabs.de/mnemos/internal/domain"
	"go.klarlabs.de/mnemos/internal/llm"
)

// mockLLMClient is a test double for llm.Client.
type mockLLMClient struct {
	response string
	err      error
	calls    int
}

func (m *mockLLMClient) Complete(_ context.Context, _ []llm.Message) (llm.Response, error) {
	m.calls++
	if m.err != nil {
		return llm.Response{}, m.err
	}
	return llm.Response{Content: m.response, Model: "test-model", InputTokens: 10, OutputTokens: 5}, nil
}

// blockingLLMClient hangs until its context is cancelled, standing in for a
// slow local model.
type blockingLLMClient struct{ started chan struct{} }

func (b *blockingLLMClient) Complete(ctx context.Context, _ []llm.Message) (llm.Response, error) {
	select {
	case b.started <- struct{}{}:
	default:
	}
	<-ctx.Done()
	return llm.Response{}, ctx.Err()
}

// Extraction must honor the caller's deadline. It previously built its budget
// from context.Background(), detaching from the caller entirely: a hook that
// budgeted itself 90s could still block for 3x the per-request LLM timeout
// (360s by default), which is what let `hook capture` overrun any hook timeout
// Claude Code enforced. The caller's deadline must cap the extraction budget.
func TestExtractWithEntitiesHonorsCallerDeadline(t *testing.T) {
	engine := newTestLLMEngine(&blockingLLMClient{started: make(chan struct{}, 1)})
	events := []domain.Event{{ID: "ev_1", Content: "Revenue grew 15% in Q3."}}

	ctx, cancel := context.WithTimeout(context.Background(), 150*time.Millisecond)
	defer cancel()

	done := make(chan struct{})
	go func() {
		defer close(done)
		// Falls back to rule-based extraction when the LLM call fails; we only
		// care that it returns promptly rather than running the full budget.
		_, _, _, _ = engine.ExtractWithEntities(ctx, events)
	}()

	select {
	case <-done:
	case <-time.After(10 * time.Second):
		t.Fatal("ExtractWithEntities ignored the caller's 150ms deadline; it is still " +
			"deriving its budget from context.Background()")
	}
}

// The cache is keyed on what actually produced the claims. MNEMOS_EXTRACT_MODEL
// overrides the model for extraction specifically (pipeline.NewExtractor), so
// omitting it from the key made two different models share one cache entry:
// switching extract models silently served claims generated by the previous
// one, and a "faster model" benchmark just measured a cache hit.
func TestCacheKeyVariesByExtractModel(t *testing.T) {
	engine := newTestLLMEngine(&mockLLMClient{})
	engine.cacheDir = t.TempDir() // cacheKey returns "" when unset
	texts := []string{"Revenue grew 15% in Q3."}

	t.Setenv("MNEMOS_LLM_PROVIDER", "ollama")
	t.Setenv("MNEMOS_LLM_MODEL", "qwen2.5:14b")

	t.Setenv("MNEMOS_EXTRACT_MODEL", "")
	base := engine.cacheKey(texts)

	t.Setenv("MNEMOS_EXTRACT_MODEL", "llama3.2:latest")
	overridden := engine.cacheKey(texts)

	t.Setenv("MNEMOS_EXTRACT_MODEL", "mistral:latest")
	other := engine.cacheKey(texts)

	if base == overridden {
		t.Error("cache key ignores MNEMOS_EXTRACT_MODEL; a different extract model reuses the base model's cached claims")
	}
	if overridden == other {
		t.Error("cache key does not distinguish two different MNEMOS_EXTRACT_MODEL values")
	}
	// Same inputs must still be stable, or the cache never hits.
	t.Setenv("MNEMOS_EXTRACT_MODEL", "llama3.2:latest")
	if again := engine.cacheKey(texts); again != overridden {
		t.Errorf("cache key not deterministic: %q vs %q", again, overridden)
	}
}

// countingLLMClient returns a distinct claim per call so batches are
// distinguishable in the merged output.
type countingLLMClient struct {
	calls    int
	maxChars int // largest prompt seen
	failOn   map[int]bool
}

func (c *countingLLMClient) Complete(_ context.Context, msgs []llm.Message) (llm.Response, error) {
	c.calls++
	for _, m := range msgs {
		if len(m.Content) > c.maxChars {
			c.maxChars = len(m.Content)
		}
	}
	if c.failOn[c.calls] {
		return llm.Response{}, fmt.Errorf("simulated provider failure on call %d", c.calls)
	}
	body, _ := json.Marshal([]llmClaim{
		{Text: fmt.Sprintf("Batch %d produced a measured result", c.calls), Type: "fact", Confidence: 0.9},
	})
	return llm.Response{Content: string(body), Model: "test-model"}, nil
}

// bigEvents builds n events of roughly size chars each.
func bigEvents(n, size int) []domain.Event {
	events := make([]domain.Event, 0, n)
	for i := range n {
		events = append(events, domain.Event{
			ID:      fmt.Sprintf("ev_%d", i),
			Content: fmt.Sprintf("Event %d states that ", i) + strings.Repeat("the system recorded a durable measurement. ", size/44),
		})
	}
	return events
}

// A whole session's transcript must not go to the model as one prompt. A 20KiB
// capture sent as a single request exceeded the per-request LLM timeout on a
// local model, so every attempt failed and extraction silently fell back to
// rule-based — no entities, weaker claims — while still burning the full
// budget. Splitting into bounded batches keeps each request completable.
func TestExtractBatchesLargeInput(t *testing.T) {
	t.Setenv("MNEMOS_EXTRACT_BATCH_CHARS", "2000")
	client := &countingLLMClient{}
	engine := newTestLLMEngine(client)

	// ~10KiB total, well past one batch.
	events := bigEvents(10, 1000)
	claims, _, _, err := engine.ExtractWithEntities(context.Background(), events)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if client.calls < 2 {
		t.Fatalf("expected the input to be split across multiple requests, got %d call(s)", client.calls)
	}
	// Every batch's claims must survive into the merged result.
	if len(claims) != client.calls {
		t.Errorf("got %d claims from %d batches; batch results were lost in the merge", len(claims), client.calls)
	}
	// No single request may carry the whole transcript.
	if client.maxChars > 6000 {
		t.Errorf("a single prompt carried %d chars; batching did not bound request size", client.maxChars)
	}
}

// One bad batch must not cost the whole session. Before batching, a single
// failure meant the entire capture fell back to rule-based.
func TestExtractPartialBatchFailureKeepsOtherBatches(t *testing.T) {
	t.Setenv("MNEMOS_EXTRACT_BATCH_CHARS", "2000")
	client := &countingLLMClient{failOn: map[int]bool{1: true}}
	engine := newTestLLMEngine(client)

	events := bigEvents(8, 1000)
	claims, evidence, _, err := engine.ExtractWithEntities(context.Background(), events)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(claims) == 0 {
		t.Fatal("a single failed batch wiped out every other batch's claims")
	}
	if len(evidence) != len(claims) {
		t.Errorf("evidence/claim mismatch: %d vs %d", len(evidence), len(claims))
	}
	// The failed batch's events still yield rule-based claims, so the
	// surviving set must exceed what the successful LLM batches alone gave.
	var fromLLM int
	for _, c := range claims {
		if strings.HasPrefix(c.Text, "Batch ") {
			fromLLM++
		}
	}
	if fromLLM == 0 {
		t.Error("no LLM-derived claims survived; the whole run fell back")
	}
}

func TestLLMEngineExtractFromJSON(t *testing.T) {
	claims := []llmClaim{
		{Text: "Revenue grew 15% in Q3", Type: "fact", Confidence: 0.92},
		{Text: "We will migrate to PostgreSQL", Type: "decision", Confidence: 0.88},
		{Text: "Users might prefer dark mode", Type: "hypothesis", Confidence: 0.6},
	}
	responseJSON, _ := json.Marshal(claims)

	client := &mockLLMClient{response: string(responseJSON)}
	engine := newTestLLMEngine(client)

	events := []domain.Event{
		{ID: "ev_1", Content: "Revenue grew 15% in Q3. We will migrate to PostgreSQL. Users might prefer dark mode."},
	}

	gotClaims, gotEvidence, err := engine.Extract(context.Background(), events)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if len(gotClaims) != 3 {
		t.Fatalf("expected 3 claims, got %d", len(gotClaims))
	}
	if len(gotEvidence) != 3 {
		t.Fatalf("expected 3 evidence links, got %d", len(gotEvidence))
	}

	// Verify types.
	expectedTypes := []domain.ClaimType{domain.ClaimTypeFact, domain.ClaimTypeDecision, domain.ClaimTypeHypothesis}
	for i, claim := range gotClaims {
		if claim.Type != expectedTypes[i] {
			t.Errorf("claim %d: got type %q, want %q", i, claim.Type, expectedTypes[i])
		}
	}

	// Verify confidence clamping.
	if gotClaims[2].Confidence < 0.5 {
		t.Errorf("hypothesis confidence %f should be clamped to >= 0.5", gotClaims[2].Confidence)
	}

	// Verify evidence links back to the source event.
	for _, ev := range gotEvidence {
		if ev.EventID != "ev_1" {
			t.Errorf("evidence should link to ev_1, got %q", ev.EventID)
		}
	}
}

func TestLLMEngineDeduplicates(t *testing.T) {
	claims := []llmClaim{
		{Text: "Revenue grew 15%", Type: "fact", Confidence: 0.9},
		{Text: "Revenue grew 15%", Type: "fact", Confidence: 0.9}, // duplicate
	}
	responseJSON, _ := json.Marshal(claims)

	client := &mockLLMClient{response: string(responseJSON)}
	engine := newTestLLMEngine(client)

	events := []domain.Event{{ID: "ev_1", Content: "Revenue grew 15%."}}
	gotClaims, _, err := engine.Extract(context.Background(), events)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(gotClaims) != 1 {
		t.Fatalf("expected 1 claim after dedup, got %d", len(gotClaims))
	}
}

func TestLLMEngineFallsBackOnError(t *testing.T) {
	client := &mockLLMClient{err: fmt.Errorf("network timeout")}
	engine := newTestLLMEngine(client)

	events := []domain.Event{
		{ID: "ev_1", Content: "We will use React for the frontend"},
	}

	gotClaims, gotEvidence, err := engine.Extract(context.Background(), events)
	if err != nil {
		t.Fatalf("should not error on fallback: %v", err)
	}

	// Rule-based engine should still produce at least one claim.
	if len(gotClaims) == 0 {
		t.Fatal("expected at least 1 claim from rule-based fallback")
	}
	if len(gotEvidence) == 0 {
		t.Fatal("expected at least 1 evidence link from rule-based fallback")
	}
}

func TestLLMEngineFallsBackOnBadJSON(t *testing.T) {
	client := &mockLLMClient{response: "this is not JSON"}
	engine := newTestLLMEngine(client)

	events := []domain.Event{
		{ID: "ev_1", Content: "We decided to use Go for the backend"},
	}

	gotClaims, _, err := engine.Extract(context.Background(), events)
	if err != nil {
		t.Fatalf("should not error on fallback: %v", err)
	}
	if len(gotClaims) == 0 {
		t.Fatal("expected at least 1 claim from rule-based fallback")
	}
}

func TestLLMEngineStripsMarkdownFences(t *testing.T) {
	claims := []llmClaim{
		{Text: "The server runs on port 8080", Type: "fact", Confidence: 0.85},
	}
	responseJSON, _ := json.Marshal(claims)
	fenced := "```json\n" + string(responseJSON) + "\n```"

	client := &mockLLMClient{response: fenced}
	engine := newTestLLMEngine(client)

	events := []domain.Event{{ID: "ev_1", Content: "The server runs on port 8080."}}
	gotClaims, _, err := engine.Extract(context.Background(), events)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(gotClaims) != 1 {
		t.Fatalf("expected 1 claim, got %d", len(gotClaims))
	}
}

func TestLLMEngineContestedDetection(t *testing.T) {
	claims := []llmClaim{
		{Text: "The database supports transactions", Type: "fact", Confidence: 0.9},
		{Text: "The database does not support transactions", Type: "fact", Confidence: 0.85},
	}
	responseJSON, _ := json.Marshal(claims)

	client := &mockLLMClient{response: string(responseJSON)}
	engine := newTestLLMEngine(client)

	events := []domain.Event{{ID: "ev_1", Content: "The database supports transactions. The database does not support transactions."}}
	gotClaims, _, err := engine.Extract(context.Background(), events)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(gotClaims) != 2 {
		t.Fatalf("expected 2 claims, got %d", len(gotClaims))
	}

	for _, claim := range gotClaims {
		if claim.Status != domain.ClaimStatusContested {
			t.Errorf("claim %q should be contested", claim.Text)
		}
	}
}

func TestLLMEngineMultiEventMatching(t *testing.T) {
	claims := []llmClaim{
		{Text: "Revenue grew 15%", Type: "fact", Confidence: 0.9},
		{Text: "We chose PostgreSQL", Type: "decision", Confidence: 0.88},
	}
	responseJSON, _ := json.Marshal(claims)

	client := &mockLLMClient{response: string(responseJSON)}
	engine := newTestLLMEngine(client)

	events := []domain.Event{
		{ID: "ev_1", Content: "Revenue grew 15% this quarter"},
		{ID: "ev_2", Content: "We chose PostgreSQL for the database"},
	}

	_, gotEvidence, err := engine.Extract(context.Background(), events)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(gotEvidence) != 2 {
		t.Fatalf("expected 2 evidence links, got %d", len(gotEvidence))
	}

	// Revenue claim should link to ev_1, PostgreSQL to ev_2.
	if gotEvidence[0].EventID != "ev_1" {
		t.Errorf("first claim should link to ev_1, got %q", gotEvidence[0].EventID)
	}
	if gotEvidence[1].EventID != "ev_2" {
		t.Errorf("second claim should link to ev_2, got %q", gotEvidence[1].EventID)
	}
}

func TestLLMEngineEmptyResponse(t *testing.T) {
	client := &mockLLMClient{response: "[]"}
	engine := newTestLLMEngine(client)

	events := []domain.Event{{ID: "ev_1", Content: "Hello world"}}
	gotClaims, gotEvidence, err := engine.Extract(context.Background(), events)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(gotClaims) != 0 {
		t.Fatalf("expected 0 claims, got %d", len(gotClaims))
	}
	if len(gotEvidence) != 0 {
		t.Fatalf("expected 0 evidence, got %d", len(gotEvidence))
	}
}

func TestLLMEngineUsesPersistentCache(t *testing.T) {
	claims := []llmClaim{{Text: "Revenue grew 15% in Q3", Type: "fact", Confidence: 0.92}}
	responseJSON, _ := json.Marshal(claims)

	client := &mockLLMClient{response: string(responseJSON)}
	engine := newTestLLMEngine(client)
	engine.cacheDir = t.TempDir()
	t.Setenv("MNEMOS_LLM_PROVIDER", "openai")
	t.Setenv("MNEMOS_LLM_MODEL", "gpt-4o-mini")

	events := []domain.Event{{ID: "ev_1", Content: "Revenue grew 15% in Q3."}}
	if _, _, err := engine.Extract(context.Background(), events); err != nil {
		t.Fatalf("first extract error: %v", err)
	}
	if _, _, err := engine.Extract(context.Background(), events); err != nil {
		t.Fatalf("second extract error: %v", err)
	}
	if client.calls != 1 {
		t.Fatalf("expected 1 LLM call with cache hit, got %d", client.calls)
	}
}

// TestLLMEngineUsageSinkFires verifies WithUsageSink receives the
// token counts from the underlying provider on a successful call. The
// pipeline layer relies on this to surface tokens as axi-go capability
// evidence; without it, MaxTokens budgets silently never engage.
func TestLLMEngineUsageSinkFires(t *testing.T) {
	claims := []llmClaim{{Text: "Revenue grew 15%", Type: "fact", Confidence: 0.9}}
	responseJSON, _ := json.Marshal(claims)
	client := &mockLLMClient{response: string(responseJSON)}

	var got TokenUsage
	var hits int
	engine := newTestLLMEngine(client).WithUsageSink(func(u TokenUsage) {
		got = u
		hits++
	})

	events := []domain.Event{{ID: "ev_1", Content: "Revenue grew 15%."}}
	if _, _, _, err := engine.ExtractWithEntities(context.Background(), events); err != nil {
		t.Fatalf("ExtractWithEntities: %v", err)
	}

	if hits != 1 {
		t.Fatalf("sink invocations = %d, want 1", hits)
	}
	if got.InputTokens != 10 || got.OutputTokens != 5 {
		t.Errorf("usage = %+v, want {Input:10 Output:5}", got)
	}
	if got.Model != "test-model" {
		t.Errorf("model = %q, want test-model", got.Model)
	}
}

// TestLLMEngineUsageSinkSkippedOnFallback verifies the sink does NOT
// fire when the LLM call errors and the rule-based fallback runs.
// Pinning this behaviour keeps the token-evidence path honest: zero
// tokens reported means zero tokens actually consumed.
func TestLLMEngineUsageSinkSkippedOnFallback(t *testing.T) {
	client := &mockLLMClient{err: fmt.Errorf("provider down")}
	var hits int
	engine := newTestLLMEngine(client).WithUsageSink(func(_ TokenUsage) {
		hits++
	})

	events := []domain.Event{{ID: "ev_1", Content: "We will use React for the frontend"}}
	if _, _, _, err := engine.ExtractWithEntities(context.Background(), events); err != nil {
		t.Fatalf("ExtractWithEntities: %v", err)
	}

	if hits != 0 {
		t.Errorf("sink invocations = %d, want 0 on fallback", hits)
	}
}

// TestLLMEngineSubjectClassFromLLM verifies the explicit "subject_class"
// field the v1.5+ prompt emits maps onto domain.Claim.SubjectClass, and
// that an omitted value falls back to unknown (fail-closed, non-promotable)
// when there are no subject entities to infer from.
func TestLLMEngineSubjectClassFromLLM(t *testing.T) {
	claims := []llmClaim{
		{Text: "Bella has diabetes", Type: "fact", Confidence: 0.85, SubjectClass: "individual"},
		{Text: "Golden Retrievers are predisposed to diabetes", Type: "fact", Confidence: 0.8, SubjectClass: "class"},
		{Text: "Response times averaged 45ms", Type: "fact", Confidence: 0.88},                            // omitted ⇒ unknown
		{Text: "The database was upgraded", Type: "fact", Confidence: 0.8, SubjectClass: "CLASS "},        // normalization
		{Text: "Latency dropped after the fix", Type: "fact", Confidence: 0.8, SubjectClass: "gibberish"}, // unrecognised ⇒ unknown
	}
	responseJSON, _ := json.Marshal(claims)

	client := &mockLLMClient{response: string(responseJSON)}
	engine := newTestLLMEngine(client)

	events := []domain.Event{{ID: "ev_1", Content: "Bella has diabetes. Golden Retrievers are predisposed to diabetes. Response times averaged 45ms. The database was upgraded. Latency dropped after the fix."}}
	gotClaims, _, err := engine.Extract(context.Background(), events)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(gotClaims) != 5 {
		t.Fatalf("expected 5 claims, got %d", len(gotClaims))
	}

	want := map[string]domain.SubjectClass{
		"Bella has diabetes":                            domain.SubjectClassIndividual,
		"Golden Retrievers are predisposed to diabetes": domain.SubjectClassClass,
		"Response times averaged 45ms":                  domain.SubjectClassUnknown,
		"The database was upgraded":                     domain.SubjectClassClass,
		"Latency dropped after the fix":                 domain.SubjectClassUnknown,
	}
	for _, c := range gotClaims {
		if got, ok := want[c.Text]; ok {
			if c.SubjectClass != got {
				t.Errorf("claim %q: SubjectClass = %q, want %q", c.Text, c.SubjectClass, got)
			}
		} else {
			t.Errorf("unexpected claim %q", c.Text)
		}
	}
}

// TestLLMEngineSubjectClassEntityFallback verifies that when the LLM omits
// subject_class, the class is inferred from the claim's SUBJECT entities:
// a concept subject ⇒ class, a person/org subject ⇒ individual, and an
// untyped/objects-only claim ⇒ unknown (fail-closed).
func TestLLMEngineSubjectClassEntityFallback(t *testing.T) {
	claims := []llmClaim{
		{Text: "Golden Retrievers get diabetes", Type: "fact", Confidence: 0.8, Entities: []llmClaimEntity{
			{Name: "Golden Retriever", Type: "concept", Role: "subject"},
		}},
		{Text: "Acme missed its target", Type: "fact", Confidence: 0.8, Entities: []llmClaimEntity{
			{Name: "Acme", Type: "org", Role: "subject"},
		}},
		{Text: "The migration used PostgreSQL", Type: "fact", Confidence: 0.8, Entities: []llmClaimEntity{
			{Name: "PostgreSQL", Type: "product", Role: "object"}, // object, not subject ⇒ no inference ⇒ unknown
		}},
	}
	responseJSON, _ := json.Marshal(claims)

	client := &mockLLMClient{response: string(responseJSON)}
	engine := newTestLLMEngine(client)

	events := []domain.Event{{ID: "ev_1", Content: "Golden Retrievers get diabetes. Acme missed its target. The migration used PostgreSQL."}}
	gotClaims, _, err := engine.Extract(context.Background(), events)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	want := map[string]domain.SubjectClass{
		"Golden Retrievers get diabetes": domain.SubjectClassClass,
		"Acme missed its target":         domain.SubjectClassIndividual,
		"The migration used PostgreSQL":  domain.SubjectClassUnknown,
	}
	if len(gotClaims) != len(want) {
		t.Fatalf("expected %d claims, got %d", len(want), len(gotClaims))
	}
	for _, c := range gotClaims {
		if got, ok := want[c.Text]; ok {
			if c.SubjectClass != got {
				t.Errorf("claim %q: SubjectClass = %q, want %q", c.Text, c.SubjectClass, got)
			}
		} else {
			t.Errorf("unexpected claim %q", c.Text)
		}
	}
}

// TestLLMEngineSubjectClassExplicitBeatsEntities verifies the LLM's explicit
// subject_class wins over the entity-based heuristic when both are present.
func TestLLMEngineSubjectClassExplicitBeatsEntities(t *testing.T) {
	// A concept subject entity would infer "class", but the explicit
	// "individual" hint must win (e.g. "Rex, a Golden Retriever, ...").
	claims := []llmClaim{
		{Text: "Rex the Golden Retriever has diabetes", Type: "fact", Confidence: 0.85, SubjectClass: "individual", Entities: []llmClaimEntity{
			{Name: "Golden Retriever", Type: "concept", Role: "subject"},
		}},
	}
	responseJSON, _ := json.Marshal(claims)

	client := &mockLLMClient{response: string(responseJSON)}
	engine := newTestLLMEngine(client)

	events := []domain.Event{{ID: "ev_1", Content: "Rex the Golden Retriever has diabetes."}}
	gotClaims, _, err := engine.Extract(context.Background(), events)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(gotClaims) != 1 {
		t.Fatalf("expected 1 claim, got %d", len(gotClaims))
	}
	if gotClaims[0].SubjectClass != domain.SubjectClassIndividual {
		t.Errorf("SubjectClass = %q, want individual (explicit beats entity inference)", gotClaims[0].SubjectClass)
	}
}

// TestLLMEngineRuleFallbackSubjectClassUnknown verifies the rule-based
// fallback path (LLM errored) still yields claims, all with an unknown
// subject class — the rule-based path is unchanged and never promotable.
func TestLLMEngineRuleFallbackSubjectClassUnknown(t *testing.T) {
	client := &mockLLMClient{err: fmt.Errorf("provider down")}
	engine := newTestLLMEngine(client)

	events := []domain.Event{{ID: "ev_1", Content: "We will use React for the frontend"}}
	gotClaims, _, err := engine.Extract(context.Background(), events)
	if err != nil {
		t.Fatalf("should not error on fallback: %v", err)
	}
	if len(gotClaims) == 0 {
		t.Fatal("expected at least 1 claim from rule-based fallback")
	}
	for _, c := range gotClaims {
		if c.SubjectClass != domain.SubjectClassUnknown {
			t.Errorf("rule-based claim %q: SubjectClass = %q, want unknown", c.Text, c.SubjectClass)
		}
	}
}

// newTestLLMEngine creates an LLMEngine with deterministic IDs and clock.
func newTestLLMEngine(client llm.Client) LLMEngine {
	seq := 0
	engine := NewLLMEngine(client)
	engine.now = func() time.Time { return time.Date(2025, 1, 1, 0, 0, 0, 0, time.UTC) }
	engine.cacheDir = ""
	engine.nextID = func() (string, error) {
		seq++
		return fmt.Sprintf("cl_test_%03d", seq), nil
	}
	return engine
}
