apiVersion: rollops.klarlabs.de/v1
kind: RolloutConfig
metadata:
  name: hm-svc-mnemos
spec:
  target:
    kind: kubernetes
    ref: hermes/prod/svc-mnemos
    criticality: low
    spec:
      namespace: hermes
      resource: service/mnemos
      manifest: "apiVersion: v1\nkind: Service\nmetadata:\n  name: mnemos\n  namespace:\
        \ hermes\nspec:\n  internalTrafficPolicy: Cluster\n  ports:\n  - name: http\n\
        \    port: 7777\n    protocol: TCP\n    targetPort: http\n  selector:\n  \
        \  app.kubernetes.io/name: mnemos\n  sessionAffinity: None\n  type: ClusterIP\n"
  strategy:
    type: rolling
  verification: shallow

