package main

import (
	"regexp"
	"strings"
)

// Harness-injected text is stripped from transcript content before capture
// extracts claims from it.
//
// A session transcript is not just the conversation. The harness injects
// system reminders, tool-notification blocks, skill files loaded into context,
// and the preamble it writes when a session resumes after compaction. All of
// it arrives in user-role messages, so capture read it as conversation and
// extraction dutifully turned it into claims.
//
// The cost was visible in a production brain: of 525 junk claims removed by
// hand, 78 were verbatim lines from SKILL.md files ("Write
// `./memory/sessions/[YYYY-MM-DD].md`…"), 20 were harness scaffolding
// ("<note>A task-notification fires…", "This session is being continued from a
// previous conversation"), and those claims then fed the contradiction
// detector, which paired them with unrelated work.
//
// Filtering here rather than in extraction is deliberate: this text is
// identifiable by its structure at the point it is read, and never carries
// knowledge. Extraction's junk filter (internal/extract/junk.go) stays focused
// on the harder judgement — whether a genuine human sentence asserts a fact.

// systemReminderRE matches a <system-reminder>…</system-reminder> block,
// including the multi-line case. These carry harness instructions and injected
// file contents, never conversation.
var systemReminderRE = regexp.MustCompile(`(?is)<system-reminder>.*?</system-reminder>`)

// taskNotificationRE matches the background-task notification blocks the
// harness emits, which describe agent lifecycle rather than any fact.
var taskNotificationRE = regexp.MustCompile(`(?is)<task-notification>.*?</task-notification>`)

// noteBlockRE matches the bare <note>…</note> the notification format uses.
var noteBlockRE = regexp.MustCompile(`(?is)<note>.*?</note>`)

// commandBlockRE matches the slash-command wrappers a skill invocation leaves
// in the transcript (<command-name>, <command-message>, <command-args>).
var commandBlockRE = regexp.MustCompile(`(?is)<command-(?:name|message|args)>.*?</command-(?:name|message|args)>`)

// resumePreambleRE matches the block the harness writes when a session resumes
// from a summary. It describes the session, not the work.
var resumePreambleRE = regexp.MustCompile(`(?im)^.*This session is being continued from a previous conversation.*$`)

// skillPreambleRE matches the header a loaded skill contributes. Everything
// following it in that message is skill instructions rather than conversation,
// but the header alone is the reliable marker.
var skillPreambleRE = regexp.MustCompile(`(?im)^Base directory for this skill:.*$`)

// harnessBlocks are stripped wholesale, in order.
var harnessBlocks = []*regexp.Regexp{
	systemReminderRE,
	taskNotificationRE,
	noteBlockRE,
	commandBlockRE,
	resumePreambleRE,
	skillPreambleRE,
}

// harnessLinePrefixes drop a single line when it starts with one of these.
// Each is a harness artifact with no conversational counterpart, so a prefix
// match cannot swallow real content the way a substring match could.
var harnessLinePrefixes = []string{
	"[SYSTEM NOTIFICATION - NOT USER INPUT]",
	"The summary below covers the earlier portion of the conversation",
	"Resume directly — do not acknowledge the summary",
	"Resume directly - do not acknowledge the summary",
	"Analysis:",
	"UserPromptSubmit hook additional context:",
	"SessionStart hook additional context:",
	"Caveat: The messages below were generated by the user while running local commands",
}

// stripHarnessText removes harness-injected content from one message's text.
// Returns the conversational remainder, which may be empty when the message was
// nothing but harness output — in which case capture skips it entirely.
func stripHarnessText(text string) string {
	if text == "" {
		return ""
	}
	for _, re := range harnessBlocks {
		text = re.ReplaceAllString(text, "")
	}

	var kept []string
	for line := range strings.SplitSeq(text, "\n") {
		if isHarnessLine(line) {
			continue
		}
		kept = append(kept, line)
	}
	return strings.TrimSpace(strings.Join(kept, "\n"))
}

// isHarnessLine reports whether a single line is harness scaffolding.
func isHarnessLine(line string) bool {
	trimmed := strings.TrimSpace(line)
	if trimmed == "" {
		return false // blank lines are structure; keep them for paragraphing
	}
	for _, p := range harnessLinePrefixes {
		if strings.HasPrefix(trimmed, p) {
			return true
		}
	}
	// An unclosed harness tag (the block regexes need both halves) still marks
	// a scaffolding line rather than conversation.
	return strings.HasPrefix(trimmed, "<system-reminder>") ||
		strings.HasPrefix(trimmed, "</system-reminder>") ||
		strings.HasPrefix(trimmed, "<task-notification>") ||
		strings.HasPrefix(trimmed, "</task-notification>")
}
