package config

import (
	_ "embed"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"reflect"
	"strings"
)

//go:embed config.go
var configSource []byte

// Setting is one configuration setting: its environment variable, its
// mnemos.yaml key, and what it does (the Config field's doc comment).
type Setting struct {
	Env         string
	YAML        string
	Description string
}

// Settings returns every setting in Config order. It reads config.go itself:
// the YAML key from each field's tag, the description from its doc comment,
// and the variable from the EnvOverrides table. Nothing is restated, so the
// reference built from it cannot disagree with the code that loads the file.
func Settings() ([]Setting, error) {
	f, err := parser.ParseFile(token.NewFileSet(), "config.go", configSource, parser.ParseComments)
	if err != nil {
		return nil, err
	}
	var cfg *ast.StructType
	var overrides *ast.FuncDecl
	for _, d := range f.Decls {
		switch d := d.(type) {
		case *ast.GenDecl:
			for _, s := range d.Specs {
				if ts, ok := s.(*ast.TypeSpec); ok && ts.Name.Name == "Config" {
					cfg, _ = ts.Type.(*ast.StructType)
				}
			}
		case *ast.FuncDecl:
			if d.Name.Name == "EnvOverrides" {
				overrides = d
			}
		}
	}
	if cfg == nil || overrides == nil {
		return nil, fmt.Errorf("config.go: Config struct or EnvOverrides not found")
	}

	// Go field path ("DB.URL") -> env var, from the EnvOverrides table.
	envOf := map[string]string{}
	ast.Inspect(overrides, func(n ast.Node) bool {
		lit, ok := n.(*ast.CompositeLit)
		if !ok || len(lit.Elts) != 2 {
			return true
		}
		key, ok1 := lit.Elts[0].(*ast.BasicLit)
		sel, ok2 := lit.Elts[1].(*ast.SelectorExpr)
		if !ok1 || !ok2 || key.Kind != token.STRING {
			return true
		}
		envOf[selectorPath(sel)] = strings.Trim(key.Value, `"`)
		return false
	})

	var out []Setting
	var walk func(st *ast.StructType, goPath, yamlPath []string, groupDoc string) error
	walk = func(st *ast.StructType, goPath, yamlPath []string, groupDoc string) error {
		for _, field := range st.Fields.List {
			if len(field.Names) != 1 || field.Tag == nil {
				continue
			}
			name := field.Names[0].Name
			tag := reflect.StructTag(strings.Trim(field.Tag.Value, "`")).Get("yaml")
			gp, yp := append(append([]string{}, goPath...), name), append(append([]string{}, yamlPath...), tag)
			doc := docText(field.Doc)
			if inner, ok := field.Type.(*ast.StructType); ok {
				if err := walk(inner, gp, yp, doc); err != nil {
					return err
				}
				continue
			}
			env, ok := envOf[strings.Join(gp, ".")]
			if !ok {
				return fmt.Errorf("config field %s has no EnvOverrides entry", strings.Join(gp, "."))
			}
			if doc == "" {
				// A group with a single leaf may document it on the group.
				if len(st.Fields.List) == 1 {
					doc = groupDoc
				}
			}
			out = append(out, Setting{Env: env, YAML: strings.Join(yp, "."), Description: withoutSubject(doc, name)})
		}
		return nil
	}
	if err := walk(cfg, nil, nil, ""); err != nil {
		return nil, err
	}
	return out, nil
}

func selectorPath(sel *ast.SelectorExpr) string {
	switch x := sel.X.(type) {
	case *ast.SelectorExpr:
		return selectorPath(x) + "." + sel.Sel.Name
	default:
		return sel.Sel.Name
	}
}

// withoutSubject drops the Go doc convention's leading field name, which the
// reference's own columns already give: "URL is the DSN" reads "The DSN",
// "MaxConns caps …" reads "Caps …".
func withoutSubject(doc, field string) string {
	rest, ok := strings.CutPrefix(doc, field+" ")
	if !ok {
		return doc
	}
	for _, verb := range []string{"is ", "are "} {
		if r, ok := strings.CutPrefix(rest, verb); ok {
			rest = r
			break
		}
	}
	if rest == "" {
		return doc
	}
	return strings.ToUpper(rest[:1]) + rest[1:]
}

func docText(g *ast.CommentGroup) string {
	if g == nil {
		return ""
	}
	return strings.Join(strings.Fields(g.Text()), " ")
}

// Reference renders docs/reference/configuration.md.
func Reference() (string, error) {
	settings, err := Settings()
	if err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString("<!-- Code generated by tools/configdoc from internal/config. DO NOT EDIT. -->\n\n")
	b.WriteString("# Configuration reference\n\n")
	b.WriteString("Every setting can be given as an environment variable or as a key in\n")
	b.WriteString("`mnemos.yaml`. An environment variable always wins over the file. Generated from\n")
	b.WriteString("`internal/config/config.go` (`go run ./tools/configdoc`); a test fails when this\n")
	b.WriteString("file, the code, or any `MNEMOS_*` name the code reads disagree.\n\n")
	b.WriteString("| Variable | `mnemos.yaml` key | Description |\n|---|---|---|\n")
	for _, s := range settings {
		fmt.Fprintf(&b, "| `%s` | `%s` | %s |\n", s.Env, s.YAML, escapeCell(s.Description))
	}
	b.WriteString("\n## Not configuration\n\n")
	b.WriteString("Read from the environment but deliberately not part of `mnemos.yaml`: process\n")
	b.WriteString("plumbing, diagnostics and test hooks.\n\n")
	b.WriteString("| Variable | Description |\n|---|---|\n")
	for _, v := range InternalEnv {
		fmt.Fprintf(&b, "| `%s` | %s |\n", v.Name, escapeCell(v.Description))
	}
	return b.String(), nil
}

func escapeCell(s string) string { return strings.ReplaceAll(s, "|", `\|`) }
