// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: claims.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const averageTrust = `-- name: AverageTrust :one
SELECT CAST(COALESCE(AVG(trust_score), 0) AS REAL) AS avg_trust FROM claims
`

func (q *Queries) AverageTrust(ctx context.Context) (float64, error) {
	row := q.db.QueryRowContext(ctx, averageTrust)
	var avg_trust float64
	err := row.Scan(&avg_trust)
	return avg_trust, err
}

const countClaimsBelowTrust = `-- name: CountClaimsBelowTrust :one
SELECT COUNT(*) AS n FROM claims WHERE trust_score < ?
`

func (q *Queries) CountClaimsBelowTrust(ctx context.Context, trustScore float64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countClaimsBelowTrust, trustScore)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const deleteAllClaimEvidence = `-- name: DeleteAllClaimEvidence :exec
DELETE FROM claim_evidence
`

func (q *Queries) DeleteAllClaimEvidence(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllClaimEvidence)
	return err
}

const deleteAllClaimStatusHistory = `-- name: DeleteAllClaimStatusHistory :exec
DELETE FROM claim_status_history
`

func (q *Queries) DeleteAllClaimStatusHistory(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllClaimStatusHistory)
	return err
}

const deleteAllClaims = `-- name: DeleteAllClaims :exec
DELETE FROM claims
`

func (q *Queries) DeleteAllClaims(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllClaims)
	return err
}

const deleteClaimByID = `-- name: DeleteClaimByID :exec
DELETE FROM claims WHERE id = ?
`

func (q *Queries) DeleteClaimByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteClaimByID, id)
	return err
}

const deleteClaimEvidenceByClaimID = `-- name: DeleteClaimEvidenceByClaimID :exec
DELETE FROM claim_evidence WHERE claim_id = ?
`

func (q *Queries) DeleteClaimEvidenceByClaimID(ctx context.Context, claimID string) error {
	_, err := q.db.ExecContext(ctx, deleteClaimEvidenceByClaimID, claimID)
	return err
}

const deleteClaimStatusHistoryByClaimID = `-- name: DeleteClaimStatusHistoryByClaimID :exec
DELETE FROM claim_status_history WHERE claim_id = ?
`

func (q *Queries) DeleteClaimStatusHistoryByClaimID(ctx context.Context, claimID string) error {
	_, err := q.db.ExecContext(ctx, deleteClaimStatusHistoryByClaimID, claimID)
	return err
}

const listAllClaims = `-- name: ListAllClaims :many
SELECT id, text, type, confidence, status, created_at, created_by, trust_score,
       valid_from, valid_to, last_verified, verify_count, half_life_days,
       scope_service, scope_env, scope_team,
       source_document, source_type, source_authority, liveness,
       last_executed, citation_count, provenance_rationale,
       test_id, test_requirement_ref, test_author,
       test_last_modified, test_last_run_at, test_pass_count, test_fail_count,
       visibility, confidence_components, lifecycle
FROM claims
ORDER BY created_at ASC
`

func (q *Queries) ListAllClaims(ctx context.Context) ([]Claim, error) {
	rows, err := q.db.QueryContext(ctx, listAllClaims)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Claim
	for rows.Next() {
		var i Claim
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.Type,
			&i.Confidence,
			&i.Status,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.TrustScore,
			&i.ValidFrom,
			&i.ValidTo,
			&i.LastVerified,
			&i.VerifyCount,
			&i.HalfLifeDays,
			&i.ScopeService,
			&i.ScopeEnv,
			&i.ScopeTeam,
			&i.SourceDocument,
			&i.SourceType,
			&i.SourceAuthority,
			&i.Liveness,
			&i.LastExecuted,
			&i.CitationCount,
			&i.ProvenanceRationale,
			&i.TestID,
			&i.TestRequirementRef,
			&i.TestAuthor,
			&i.TestLastModified,
			&i.TestLastRunAt,
			&i.TestPassCount,
			&i.TestFailCount,
			&i.Visibility,
			&i.ConfidenceComponents,
			&i.Lifecycle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClaimTrustInputs = `-- name: ListClaimTrustInputs :many
SELECT
  c.id              AS claim_id,
  c.confidence      AS confidence,
  COUNT(DISTINCT e.created_by) AS distinct_sources,
  COUNT(DISTINCT ce.event_id)  AS total_events,
  CAST(COALESCE(MAX(e.timestamp), '') AS TEXT) AS latest_evidence_at
FROM claims c
LEFT JOIN claim_evidence ce ON ce.claim_id = c.id
LEFT JOIN events e          ON e.id = ce.event_id
GROUP BY c.id, c.confidence
`

type ListClaimTrustInputsRow struct {
	ClaimID          string  `json:"claim_id"`
	Confidence       float64 `json:"confidence"`
	DistinctSources  int64   `json:"distinct_sources"`
	TotalEvents      int64   `json:"total_events"`
	LatestEvidenceAt string  `json:"latest_evidence_at"`
}

// Inputs to recompute trust_score for every claim: confidence, the count of
// DISTINCT evidence-event authors and of total events (so corroboration can be
// graded by independence - an echo-chamber guard), and the most-recent evidence
// timestamp. LEFT JOIN so claims with no evidence still appear; the caller treats
// the missing aggregate as 0/empty.
func (q *Queries) ListClaimTrustInputs(ctx context.Context) ([]ListClaimTrustInputsRow, error) {
	rows, err := q.db.QueryContext(ctx, listClaimTrustInputs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClaimTrustInputsRow
	for rows.Next() {
		var i ListClaimTrustInputsRow
		if err := rows.Scan(
			&i.ClaimID,
			&i.Confidence,
			&i.DistinctSources,
			&i.TotalEvents,
			&i.LatestEvidenceAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClaimsByTestRequirementRef = `-- name: ListClaimsByTestRequirementRef :many
SELECT id, text, type, confidence, status, created_at, created_by, trust_score,
       valid_from, valid_to, last_verified, verify_count, half_life_days,
       scope_service, scope_env, scope_team,
       source_document, source_type, source_authority, liveness,
       last_executed, citation_count, provenance_rationale,
       test_id, test_requirement_ref, test_author,
       test_last_modified, test_last_run_at, test_pass_count, test_fail_count,
       visibility, confidence_components, lifecycle
FROM claims
WHERE type = 'test_result'
  AND test_requirement_ref = ?
ORDER BY test_last_run_at DESC, created_at DESC
`

// Filter to test_result claims sharing a TestRequirementRef. Drives
// `mnemos trust --test=<ref>` and the which_test_to_trust MCP tool: the
// previous implementation called ListAllClaims and filtered in Go,
// which scaled O(n) per invocation.
func (q *Queries) ListClaimsByTestRequirementRef(ctx context.Context, testRequirementRef string) ([]Claim, error) {
	rows, err := q.db.QueryContext(ctx, listClaimsByTestRequirementRef, testRequirementRef)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Claim
	for rows.Next() {
		var i Claim
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.Type,
			&i.Confidence,
			&i.Status,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.TrustScore,
			&i.ValidFrom,
			&i.ValidTo,
			&i.LastVerified,
			&i.VerifyCount,
			&i.HalfLifeDays,
			&i.ScopeService,
			&i.ScopeEnv,
			&i.ScopeTeam,
			&i.SourceDocument,
			&i.SourceType,
			&i.SourceAuthority,
			&i.Liveness,
			&i.LastExecuted,
			&i.CitationCount,
			&i.ProvenanceRationale,
			&i.TestID,
			&i.TestRequirementRef,
			&i.TestAuthor,
			&i.TestLastModified,
			&i.TestLastRunAt,
			&i.TestPassCount,
			&i.TestFailCount,
			&i.Visibility,
			&i.ConfidenceComponents,
			&i.Lifecycle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markClaimVerified = `-- name: MarkClaimVerified :exec
UPDATE claims
SET last_verified = ?,
    verify_count = verify_count + 1,
    half_life_days = CASE WHEN ? > 0 THEN ? ELSE half_life_days END
WHERE id = ?
`

type MarkClaimVerifiedParams struct {
	LastVerified string      `json:"last_verified"`
	Column2      interface{} `json:"column_2"`
	HalfLifeDays float64     `json:"half_life_days"`
	ID           string      `json:"id"`
}

// Bumps last_verified to the supplied timestamp and increments
// verify_count by one. The half_life_days COALESCE keeps any
// existing override when the caller passes 0 (sqlc binds it as the
// third parameter); a non-zero value replaces the override.
func (q *Queries) MarkClaimVerified(ctx context.Context, arg MarkClaimVerifiedParams) error {
	_, err := q.db.ExecContext(ctx, markClaimVerified,
		arg.LastVerified,
		arg.Column2,
		arg.HalfLifeDays,
		arg.ID,
	)
	return err
}

const setClaimValidity = `-- name: SetClaimValidity :exec
UPDATE claims SET valid_to = ? WHERE id = ?
`

type SetClaimValidityParams struct {
	ValidTo sql.NullString `json:"valid_to"`
	ID      string         `json:"id"`
}

// Atomic supersession primitive: mark a claim as no longer valid as
// of the given timestamp. Pass NULL to clear valid_to (un-supersede
// the claim), useful when a resolution is reverted.
func (q *Queries) SetClaimValidity(ctx context.Context, arg SetClaimValidityParams) error {
	_, err := q.db.ExecContext(ctx, setClaimValidity, arg.ValidTo, arg.ID)
	return err
}

const updateClaimTrust = `-- name: UpdateClaimTrust :exec
UPDATE claims SET trust_score = ? WHERE id = ?
`

type UpdateClaimTrustParams struct {
	TrustScore float64 `json:"trust_score"`
	ID         string  `json:"id"`
}

func (q *Queries) UpdateClaimTrust(ctx context.Context, arg UpdateClaimTrustParams) error {
	_, err := q.db.ExecContext(ctx, updateClaimTrust, arg.TrustScore, arg.ID)
	return err
}

const upsertClaim = `-- name: UpsertClaim :exec
INSERT INTO claims (id, text, type, confidence, status, created_at, created_by, valid_from, scope_service, scope_env, scope_team, source_document, source_type, source_authority, liveness, last_executed, citation_count, provenance_rationale, test_id, test_requirement_ref, test_author, test_last_modified, test_last_run_at, test_pass_count, test_fail_count, visibility, confidence_components, lifecycle)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  text = excluded.text,
  type = excluded.type,
  confidence = excluded.confidence,
  status = excluded.status,
  created_at = excluded.created_at,
  created_by = excluded.created_by,
  valid_from = excluded.valid_from,
  scope_service = excluded.scope_service,
  scope_env = excluded.scope_env,
  scope_team = excluded.scope_team,
  source_document = excluded.source_document,
  source_type = excluded.source_type,
  source_authority = excluded.source_authority,
  liveness = excluded.liveness,
  last_executed = excluded.last_executed,
  citation_count = excluded.citation_count,
  provenance_rationale = excluded.provenance_rationale,
  test_id = excluded.test_id,
  test_requirement_ref = excluded.test_requirement_ref,
  test_author = excluded.test_author,
  test_last_modified = excluded.test_last_modified,
  test_last_run_at = excluded.test_last_run_at,
  test_pass_count = excluded.test_pass_count,
  test_fail_count = excluded.test_fail_count,
  visibility = excluded.visibility,
  confidence_components = excluded.confidence_components,
  lifecycle = excluded.lifecycle
`

type UpsertClaimParams struct {
	ID                   string  `json:"id"`
	Text                 string  `json:"text"`
	Type                 string  `json:"type"`
	Confidence           float64 `json:"confidence"`
	Status               string  `json:"status"`
	CreatedAt            string  `json:"created_at"`
	CreatedBy            string  `json:"created_by"`
	ValidFrom            string  `json:"valid_from"`
	ScopeService         string  `json:"scope_service"`
	ScopeEnv             string  `json:"scope_env"`
	ScopeTeam            string  `json:"scope_team"`
	SourceDocument       string  `json:"source_document"`
	SourceType           string  `json:"source_type"`
	SourceAuthority      float64 `json:"source_authority"`
	Liveness             string  `json:"liveness"`
	LastExecuted         string  `json:"last_executed"`
	CitationCount        int64   `json:"citation_count"`
	ProvenanceRationale  string  `json:"provenance_rationale"`
	TestID               string  `json:"test_id"`
	TestRequirementRef   string  `json:"test_requirement_ref"`
	TestAuthor           string  `json:"test_author"`
	TestLastModified     string  `json:"test_last_modified"`
	TestLastRunAt        string  `json:"test_last_run_at"`
	TestPassCount        int64   `json:"test_pass_count"`
	TestFailCount        int64   `json:"test_fail_count"`
	Visibility           string  `json:"visibility"`
	ConfidenceComponents string  `json:"confidence_components"`
	Lifecycle            string  `json:"lifecycle"`
}

// ON CONFLICT preserves trust_score and valid_to (computed/managed
// separately via UpdateClaimTrust and SetClaimValidity), but does
// refresh valid_from: re-extracting a claim with newer evidence is
// a legitimate "this fact is observed again from <ts>" signal.
func (q *Queries) UpsertClaim(ctx context.Context, arg UpsertClaimParams) error {
	_, err := q.db.ExecContext(ctx, upsertClaim,
		arg.ID,
		arg.Text,
		arg.Type,
		arg.Confidence,
		arg.Status,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.ValidFrom,
		arg.ScopeService,
		arg.ScopeEnv,
		arg.ScopeTeam,
		arg.SourceDocument,
		arg.SourceType,
		arg.SourceAuthority,
		arg.Liveness,
		arg.LastExecuted,
		arg.CitationCount,
		arg.ProvenanceRationale,
		arg.TestID,
		arg.TestRequirementRef,
		arg.TestAuthor,
		arg.TestLastModified,
		arg.TestLastRunAt,
		arg.TestPassCount,
		arg.TestFailCount,
		arg.Visibility,
		arg.ConfidenceComponents,
		arg.Lifecycle,
	)
	return err
}

const upsertClaimEvidence = `-- name: UpsertClaimEvidence :exec
INSERT INTO claim_evidence (claim_id, event_id)
VALUES (?, ?)
ON CONFLICT(claim_id, event_id) DO NOTHING
`

type UpsertClaimEvidenceParams struct {
	ClaimID string `json:"claim_id"`
	EventID string `json:"event_id"`
}

func (q *Queries) UpsertClaimEvidence(ctx context.Context, arg UpsertClaimEvidenceParams) error {
	_, err := q.db.ExecContext(ctx, upsertClaimEvidence, arg.ClaimID, arg.EventID)
	return err
}
