// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: decisions.sql

package sqlcgen

import (
	"context"
)

const appendDecisionBelief = `-- name: AppendDecisionBelief :exec
INSERT INTO decision_beliefs (decision_id, claim_id)
VALUES (?, ?)
ON CONFLICT(decision_id, claim_id) DO NOTHING
`

type AppendDecisionBeliefParams struct {
	DecisionID string `json:"decision_id"`
	ClaimID    string `json:"claim_id"`
}

func (q *Queries) AppendDecisionBelief(ctx context.Context, arg AppendDecisionBeliefParams) error {
	_, err := q.db.ExecContext(ctx, appendDecisionBelief, arg.DecisionID, arg.ClaimID)
	return err
}

const attachDecisionOutcome = `-- name: AttachDecisionOutcome :exec
UPDATE decisions SET outcome_id = ? WHERE id = ?
`

type AttachDecisionOutcomeParams struct {
	OutcomeID string `json:"outcome_id"`
	ID        string `json:"id"`
}

func (q *Queries) AttachDecisionOutcome(ctx context.Context, arg AttachDecisionOutcomeParams) error {
	_, err := q.db.ExecContext(ctx, attachDecisionOutcome, arg.OutcomeID, arg.ID)
	return err
}

const countDecisions = `-- name: CountDecisions :one
SELECT COUNT(*) FROM decisions
`

func (q *Queries) CountDecisions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDecisions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDecision = `-- name: CreateDecision :exec
INSERT INTO decisions (id, statement, plan, reasoning, risk_level, alternatives_json, outcome_id, chosen_at, created_by, created_at, scope_service, scope_env, scope_team, refuted_beliefs_json, failed_outcome_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  statement = excluded.statement,
  plan = excluded.plan,
  reasoning = excluded.reasoning,
  risk_level = excluded.risk_level,
  alternatives_json = excluded.alternatives_json,
  outcome_id = excluded.outcome_id,
  refuted_beliefs_json = excluded.refuted_beliefs_json,
  failed_outcome_id = excluded.failed_outcome_id
`

type CreateDecisionParams struct {
	ID                 string `json:"id"`
	Statement          string `json:"statement"`
	Plan               string `json:"plan"`
	Reasoning          string `json:"reasoning"`
	RiskLevel          string `json:"risk_level"`
	AlternativesJson   string `json:"alternatives_json"`
	OutcomeID          string `json:"outcome_id"`
	ChosenAt           string `json:"chosen_at"`
	CreatedBy          string `json:"created_by"`
	CreatedAt          string `json:"created_at"`
	ScopeService       string `json:"scope_service"`
	ScopeEnv           string `json:"scope_env"`
	ScopeTeam          string `json:"scope_team"`
	RefutedBeliefsJson string `json:"refuted_beliefs_json"`
	FailedOutcomeID    string `json:"failed_outcome_id"`
}

// WARNING (sqlc v1.30.0 bug): do NOT place a comment line between a `-- name:`
// directive and its query. A doc comment AFTER `-- name:` shifts sqlc's byte
// offsets and corrupts EVERY generated query in this file (scrambled/truncated
// SQL strings). Put per-query docs BEFORE the `-- name:` line, as below.
//
// CreateDecision is idempotent on id. Re-recording the same decision id refreshes
// statement, plan, reasoning, risk_level, alternatives, outcome_id, refuted_beliefs_json,
// and failed_outcome_id but preserves chosen_at and created_at (the original decision
// moment is the load-bearing fact).
func (q *Queries) CreateDecision(ctx context.Context, arg CreateDecisionParams) error {
	_, err := q.db.ExecContext(ctx, createDecision,
		arg.ID,
		arg.Statement,
		arg.Plan,
		arg.Reasoning,
		arg.RiskLevel,
		arg.AlternativesJson,
		arg.OutcomeID,
		arg.ChosenAt,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ScopeService,
		arg.ScopeEnv,
		arg.ScopeTeam,
		arg.RefutedBeliefsJson,
		arg.FailedOutcomeID,
	)
	return err
}

const deleteAllDecisionBeliefs = `-- name: DeleteAllDecisionBeliefs :exec
DELETE FROM decision_beliefs
`

func (q *Queries) DeleteAllDecisionBeliefs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllDecisionBeliefs)
	return err
}

const deleteAllDecisions = `-- name: DeleteAllDecisions :exec
DELETE FROM decisions
`

func (q *Queries) DeleteAllDecisions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllDecisions)
	return err
}

const deleteDecisionBeliefs = `-- name: DeleteDecisionBeliefs :exec
DELETE FROM decision_beliefs WHERE decision_id = ?
`

func (q *Queries) DeleteDecisionBeliefs(ctx context.Context, decisionID string) error {
	_, err := q.db.ExecContext(ctx, deleteDecisionBeliefs, decisionID)
	return err
}

const getDecisionByID = `-- name: GetDecisionByID :one
SELECT id, statement, plan, reasoning, risk_level, alternatives_json, outcome_id, chosen_at, created_by, created_at, scope_service, scope_env, scope_team, refuted_beliefs_json, failed_outcome_id
FROM decisions
WHERE id = ?
`

func (q *Queries) GetDecisionByID(ctx context.Context, id string) (Decision, error) {
	row := q.db.QueryRowContext(ctx, getDecisionByID, id)
	var i Decision
	err := row.Scan(
		&i.ID,
		&i.Statement,
		&i.Plan,
		&i.Reasoning,
		&i.RiskLevel,
		&i.AlternativesJson,
		&i.OutcomeID,
		&i.ChosenAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ScopeService,
		&i.ScopeEnv,
		&i.ScopeTeam,
		&i.RefutedBeliefsJson,
		&i.FailedOutcomeID,
	)
	return i, err
}

const listAllDecisions = `-- name: ListAllDecisions :many
SELECT id, statement, plan, reasoning, risk_level, alternatives_json, outcome_id, chosen_at, created_by, created_at, scope_service, scope_env, scope_team, refuted_beliefs_json, failed_outcome_id
FROM decisions
ORDER BY chosen_at DESC
`

func (q *Queries) ListAllDecisions(ctx context.Context) ([]Decision, error) {
	rows, err := q.db.QueryContext(ctx, listAllDecisions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Decision
	for rows.Next() {
		var i Decision
		if err := rows.Scan(
			&i.ID,
			&i.Statement,
			&i.Plan,
			&i.Reasoning,
			&i.RiskLevel,
			&i.AlternativesJson,
			&i.OutcomeID,
			&i.ChosenAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ScopeService,
			&i.ScopeEnv,
			&i.ScopeTeam,
			&i.RefutedBeliefsJson,
			&i.FailedOutcomeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDecisionBeliefs = `-- name: ListDecisionBeliefs :many
SELECT decision_id, claim_id
FROM decision_beliefs
WHERE decision_id = ?
`

func (q *Queries) ListDecisionBeliefs(ctx context.Context, decisionID string) ([]DecisionBelief, error) {
	rows, err := q.db.QueryContext(ctx, listDecisionBeliefs, decisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DecisionBelief
	for rows.Next() {
		var i DecisionBelief
		if err := rows.Scan(&i.DecisionID, &i.ClaimID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDecisionsByRiskLevel = `-- name: ListDecisionsByRiskLevel :many
SELECT id, statement, plan, reasoning, risk_level, alternatives_json, outcome_id, chosen_at, created_by, created_at, scope_service, scope_env, scope_team, refuted_beliefs_json, failed_outcome_id
FROM decisions
WHERE risk_level = ?
ORDER BY chosen_at DESC
`

func (q *Queries) ListDecisionsByRiskLevel(ctx context.Context, riskLevel string) ([]Decision, error) {
	rows, err := q.db.QueryContext(ctx, listDecisionsByRiskLevel, riskLevel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Decision
	for rows.Next() {
		var i Decision
		if err := rows.Scan(
			&i.ID,
			&i.Statement,
			&i.Plan,
			&i.Reasoning,
			&i.RiskLevel,
			&i.AlternativesJson,
			&i.OutcomeID,
			&i.ChosenAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ScopeService,
			&i.ScopeEnv,
			&i.ScopeTeam,
			&i.RefutedBeliefsJson,
			&i.FailedOutcomeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
