// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lessons.sql

package sqlcgen

import (
	"context"
)

const appendLessonEvidence = `-- name: AppendLessonEvidence :exec
INSERT INTO lesson_evidence (lesson_id, action_id)
VALUES (?, ?)
ON CONFLICT(lesson_id, action_id) DO NOTHING
`

type AppendLessonEvidenceParams struct {
	LessonID string `json:"lesson_id"`
	ActionID string `json:"action_id"`
}

// Idempotent on the composite key so re-running synthesis doesn't
// duplicate evidence rows.
func (q *Queries) AppendLessonEvidence(ctx context.Context, arg AppendLessonEvidenceParams) error {
	_, err := q.db.ExecContext(ctx, appendLessonEvidence, arg.LessonID, arg.ActionID)
	return err
}

const countLessons = `-- name: CountLessons :one
SELECT COUNT(*) FROM lessons
`

func (q *Queries) CountLessons(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLessons)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLesson = `-- name: CreateLesson :exec
INSERT INTO lessons (id, statement, scope_service, scope_env, scope_team, trigger, kind, confidence, derived_at, last_verified, source, created_by, polarity, subject_class)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  statement = excluded.statement,
  confidence = excluded.confidence,
  last_verified = excluded.last_verified,
  derived_at = excluded.derived_at,
  polarity = excluded.polarity,
  subject_class = excluded.subject_class
`

type CreateLessonParams struct {
	ID           string  `json:"id"`
	Statement    string  `json:"statement"`
	ScopeService string  `json:"scope_service"`
	ScopeEnv     string  `json:"scope_env"`
	ScopeTeam    string  `json:"scope_team"`
	Trigger      string  `json:"trigger"`
	Kind         string  `json:"kind"`
	Confidence   float64 `json:"confidence"`
	DerivedAt    string  `json:"derived_at"`
	LastVerified string  `json:"last_verified"`
	Source       string  `json:"source"`
	CreatedBy    string  `json:"created_by"`
	Polarity     string  `json:"polarity"`
	SubjectClass string  `json:"subject_class"`
}

// Idempotent on id. Updates statement/confidence/last_verified on
// conflict so re-running synthesis with stronger evidence ratchets
// the confidence forward without churning the row's identity.
func (q *Queries) CreateLesson(ctx context.Context, arg CreateLessonParams) error {
	_, err := q.db.ExecContext(ctx, createLesson,
		arg.ID,
		arg.Statement,
		arg.ScopeService,
		arg.ScopeEnv,
		arg.ScopeTeam,
		arg.Trigger,
		arg.Kind,
		arg.Confidence,
		arg.DerivedAt,
		arg.LastVerified,
		arg.Source,
		arg.CreatedBy,
		arg.Polarity,
		arg.SubjectClass,
	)
	return err
}

const deleteAllLessonEvidence = `-- name: DeleteAllLessonEvidence :exec
DELETE FROM lesson_evidence
`

func (q *Queries) DeleteAllLessonEvidence(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllLessonEvidence)
	return err
}

const deleteAllLessons = `-- name: DeleteAllLessons :exec
DELETE FROM lessons
`

func (q *Queries) DeleteAllLessons(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllLessons)
	return err
}

const deleteLessonEvidence = `-- name: DeleteLessonEvidence :exec
DELETE FROM lesson_evidence WHERE lesson_id = ?
`

func (q *Queries) DeleteLessonEvidence(ctx context.Context, lessonID string) error {
	_, err := q.db.ExecContext(ctx, deleteLessonEvidence, lessonID)
	return err
}

const getLessonByID = `-- name: GetLessonByID :one
SELECT id, statement, scope_service, scope_env, scope_team, trigger, kind, confidence, derived_at, last_verified, source, created_by, polarity, subject_class
FROM lessons
WHERE id = ?
`

func (q *Queries) GetLessonByID(ctx context.Context, id string) (Lesson, error) {
	row := q.db.QueryRowContext(ctx, getLessonByID, id)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.Statement,
		&i.ScopeService,
		&i.ScopeEnv,
		&i.ScopeTeam,
		&i.Trigger,
		&i.Kind,
		&i.Confidence,
		&i.DerivedAt,
		&i.LastVerified,
		&i.Source,
		&i.CreatedBy,
		&i.Polarity,
		&i.SubjectClass,
	)
	return i, err
}

const listAllLessons = `-- name: ListAllLessons :many
SELECT id, statement, scope_service, scope_env, scope_team, trigger, kind, confidence, derived_at, last_verified, source, created_by, polarity, subject_class
FROM lessons
ORDER BY confidence DESC, derived_at DESC
`

func (q *Queries) ListAllLessons(ctx context.Context) ([]Lesson, error) {
	rows, err := q.db.QueryContext(ctx, listAllLessons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lesson
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.ID,
			&i.Statement,
			&i.ScopeService,
			&i.ScopeEnv,
			&i.ScopeTeam,
			&i.Trigger,
			&i.Kind,
			&i.Confidence,
			&i.DerivedAt,
			&i.LastVerified,
			&i.Source,
			&i.CreatedBy,
			&i.Polarity,
			&i.SubjectClass,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLessonEvidence = `-- name: ListLessonEvidence :many
SELECT lesson_id, action_id
FROM lesson_evidence
WHERE lesson_id = ?
`

func (q *Queries) ListLessonEvidence(ctx context.Context, lessonID string) ([]LessonEvidence, error) {
	rows, err := q.db.QueryContext(ctx, listLessonEvidence, lessonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LessonEvidence
	for rows.Next() {
		var i LessonEvidence
		if err := rows.Scan(&i.LessonID, &i.ActionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLessonsByService = `-- name: ListLessonsByService :many
SELECT id, statement, scope_service, scope_env, scope_team, trigger, kind, confidence, derived_at, last_verified, source, created_by, polarity, subject_class
FROM lessons
WHERE scope_service = ?
ORDER BY confidence DESC, derived_at DESC
`

func (q *Queries) ListLessonsByService(ctx context.Context, scopeService string) ([]Lesson, error) {
	rows, err := q.db.QueryContext(ctx, listLessonsByService, scopeService)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lesson
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.ID,
			&i.Statement,
			&i.ScopeService,
			&i.ScopeEnv,
			&i.ScopeTeam,
			&i.Trigger,
			&i.Kind,
			&i.Confidence,
			&i.DerivedAt,
			&i.LastVerified,
			&i.Source,
			&i.CreatedBy,
			&i.Polarity,
			&i.SubjectClass,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLessonsByTrigger = `-- name: ListLessonsByTrigger :many
SELECT id, statement, scope_service, scope_env, scope_team, trigger, kind, confidence, derived_at, last_verified, source, created_by, polarity, subject_class
FROM lessons
WHERE trigger = ?
ORDER BY confidence DESC, derived_at DESC
`

func (q *Queries) ListLessonsByTrigger(ctx context.Context, trigger string) ([]Lesson, error) {
	rows, err := q.db.QueryContext(ctx, listLessonsByTrigger, trigger)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lesson
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.ID,
			&i.Statement,
			&i.ScopeService,
			&i.ScopeEnv,
			&i.ScopeTeam,
			&i.Trigger,
			&i.Kind,
			&i.Confidence,
			&i.DerivedAt,
			&i.LastVerified,
			&i.Source,
			&i.CreatedBy,
			&i.Polarity,
			&i.SubjectClass,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
