// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
)

type Action struct {
	ID           string `json:"id"`
	RunID        string `json:"run_id"`
	Kind         string `json:"kind"`
	Subject      string `json:"subject"`
	Actor        string `json:"actor"`
	At           string `json:"at"`
	MetadataJson string `json:"metadata_json"`
	CreatedBy    string `json:"created_by"`
	CreatedAt    string `json:"created_at"`
}

type Agent struct {
	ID              string `json:"id"`
	Name            string `json:"name"`
	OwnerID         string `json:"owner_id"`
	ScopesJson      string `json:"scopes_json"`
	AllowedRunsJson string `json:"allowed_runs_json"`
	Status          string `json:"status"`
	CreatedAt       string `json:"created_at"`
}

type Claim struct {
	ID                   string         `json:"id"`
	Text                 string         `json:"text"`
	Type                 string         `json:"type"`
	Confidence           float64        `json:"confidence"`
	Status               string         `json:"status"`
	CreatedAt            string         `json:"created_at"`
	CreatedBy            string         `json:"created_by"`
	TrustScore           float64        `json:"trust_score"`
	ValidFrom            string         `json:"valid_from"`
	ValidTo              sql.NullString `json:"valid_to"`
	LastVerified         string         `json:"last_verified"`
	VerifyCount          int64          `json:"verify_count"`
	HalfLifeDays         float64        `json:"half_life_days"`
	ScopeService         string         `json:"scope_service"`
	ScopeEnv             string         `json:"scope_env"`
	ScopeTeam            string         `json:"scope_team"`
	SourceDocument       string         `json:"source_document"`
	SourceType           string         `json:"source_type"`
	SourceAuthority      float64        `json:"source_authority"`
	Liveness             string         `json:"liveness"`
	LastExecuted         string         `json:"last_executed"`
	CitationCount        int64          `json:"citation_count"`
	ProvenanceRationale  string         `json:"provenance_rationale"`
	TestID               string         `json:"test_id"`
	TestRequirementRef   string         `json:"test_requirement_ref"`
	TestAuthor           string         `json:"test_author"`
	TestLastModified     string         `json:"test_last_modified"`
	TestLastRunAt        string         `json:"test_last_run_at"`
	TestPassCount        int64          `json:"test_pass_count"`
	TestFailCount        int64          `json:"test_fail_count"`
	Visibility           string         `json:"visibility"`
	ConfidenceComponents string         `json:"confidence_components"`
	Lifecycle            string         `json:"lifecycle"`
	SubjectClass         string         `json:"subject_class"`
}

type ClaimEntity struct {
	ClaimID  string `json:"claim_id"`
	EntityID string `json:"entity_id"`
	Role     string `json:"role"`
}

type ClaimEvidence struct {
	ClaimID string `json:"claim_id"`
	EventID string `json:"event_id"`
}

type ClaimStatusHistory struct {
	ID         int64  `json:"id"`
	ClaimID    string `json:"claim_id"`
	FromStatus string `json:"from_status"`
	ToStatus   string `json:"to_status"`
	ChangedAt  string `json:"changed_at"`
	Reason     string `json:"reason"`
	ChangedBy  string `json:"changed_by"`
}

type CompilationJob struct {
	ID        string `json:"id"`
	Kind      string `json:"kind"`
	Status    string `json:"status"`
	ScopeJson string `json:"scope_json"`
	StartedAt string `json:"started_at"`
	UpdatedAt string `json:"updated_at"`
	Error     string `json:"error"`
}

type Decision struct {
	ID                 string `json:"id"`
	Statement          string `json:"statement"`
	Plan               string `json:"plan"`
	Reasoning          string `json:"reasoning"`
	RiskLevel          string `json:"risk_level"`
	AlternativesJson   string `json:"alternatives_json"`
	OutcomeID          string `json:"outcome_id"`
	ChosenAt           string `json:"chosen_at"`
	CreatedBy          string `json:"created_by"`
	CreatedAt          string `json:"created_at"`
	ScopeService       string `json:"scope_service"`
	ScopeEnv           string `json:"scope_env"`
	ScopeTeam          string `json:"scope_team"`
	RefutedBeliefsJson string `json:"refuted_beliefs_json"`
	FailedOutcomeID    string `json:"failed_outcome_id"`
}

type DecisionBelief struct {
	DecisionID string `json:"decision_id"`
	ClaimID    string `json:"claim_id"`
}

type Embedding struct {
	EntityID   string `json:"entity_id"`
	EntityType string `json:"entity_type"`
	Vector     []byte `json:"vector"`
	Model      string `json:"model"`
	Dimensions int64  `json:"dimensions"`
	CreatedAt  string `json:"created_at"`
	CreatedBy  string `json:"created_by"`
}

type Entity struct {
	ID             string `json:"id"`
	Name           string `json:"name"`
	NormalizedName string `json:"normalized_name"`
	Type           string `json:"type"`
	CreatedAt      string `json:"created_at"`
	CreatedBy      string `json:"created_by"`
}

type EntityRelationship struct {
	ID        string `json:"id"`
	Kind      string `json:"kind"`
	FromID    string `json:"from_id"`
	FromType  string `json:"from_type"`
	ToID      string `json:"to_id"`
	ToType    string `json:"to_type"`
	CreatedAt string `json:"created_at"`
	CreatedBy string `json:"created_by"`
}

type Event struct {
	ID            string `json:"id"`
	RunID         string `json:"run_id"`
	SchemaVersion string `json:"schema_version"`
	Content       string `json:"content"`
	SourceInputID string `json:"source_input_id"`
	Timestamp     string `json:"timestamp"`
	MetadataJson  string `json:"metadata_json"`
	IngestedAt    string `json:"ingested_at"`
	CreatedBy     string `json:"created_by"`
}

type Lesson struct {
	ID           string  `json:"id"`
	Statement    string  `json:"statement"`
	ScopeService string  `json:"scope_service"`
	ScopeEnv     string  `json:"scope_env"`
	ScopeTeam    string  `json:"scope_team"`
	Trigger      string  `json:"trigger"`
	Kind         string  `json:"kind"`
	Confidence   float64 `json:"confidence"`
	DerivedAt    string  `json:"derived_at"`
	LastVerified string  `json:"last_verified"`
	Source       string  `json:"source"`
	CreatedBy    string  `json:"created_by"`
	Polarity     string  `json:"polarity"`
	SubjectClass string  `json:"subject_class"`
}

type LessonEvidence struct {
	LessonID string `json:"lesson_id"`
	ActionID string `json:"action_id"`
}

type LessonVersion struct {
	VersionID   int64  `json:"version_id"`
	LessonID    string `json:"lesson_id"`
	PayloadJson string `json:"payload_json"`
	ValidFrom   string `json:"valid_from"`
	ValidTo     string `json:"valid_to"`
}

type Outcome struct {
	ID          string `json:"id"`
	ActionID    string `json:"action_id"`
	Result      string `json:"result"`
	MetricsJson string `json:"metrics_json"`
	Notes       string `json:"notes"`
	ObservedAt  string `json:"observed_at"`
	Source      string `json:"source"`
	CreatedBy   string `json:"created_by"`
	CreatedAt   string `json:"created_at"`
}

type Playbook struct {
	ID           string  `json:"id"`
	Trigger      string  `json:"trigger"`
	Statement    string  `json:"statement"`
	ScopeService string  `json:"scope_service"`
	ScopeEnv     string  `json:"scope_env"`
	ScopeTeam    string  `json:"scope_team"`
	StepsJson    string  `json:"steps_json"`
	Confidence   float64 `json:"confidence"`
	DerivedAt    string  `json:"derived_at"`
	LastVerified string  `json:"last_verified"`
	Source       string  `json:"source"`
	CreatedBy    string  `json:"created_by"`
}

type PlaybookLesson struct {
	PlaybookID string `json:"playbook_id"`
	LessonID   string `json:"lesson_id"`
}

type PlaybookVersion struct {
	VersionID   int64  `json:"version_id"`
	PlaybookID  string `json:"playbook_id"`
	PayloadJson string `json:"payload_json"`
	ValidFrom   string `json:"valid_from"`
	ValidTo     string `json:"valid_to"`
}

type Relationship struct {
	ID          string `json:"id"`
	Type        string `json:"type"`
	FromClaimID string `json:"from_claim_id"`
	ToClaimID   string `json:"to_claim_id"`
	CreatedAt   string `json:"created_at"`
	CreatedBy   string `json:"created_by"`
}

type RevokedToken struct {
	Jti       string `json:"jti"`
	RevokedAt string `json:"revoked_at"`
	ExpiresAt string `json:"expires_at"`
}

type User struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	Email      string `json:"email"`
	Status     string `json:"status"`
	ScopesJson string `json:"scopes_json"`
	CreatedAt  string `json:"created_at"`
}
