// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: relationships.sql

package sqlcgen

import (
	"context"
)

const deleteAllRelationships = `-- name: DeleteAllRelationships :exec
DELETE FROM relationships
`

func (q *Queries) DeleteAllRelationships(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllRelationships)
	return err
}

const deleteRelationshipsByClaimID = `-- name: DeleteRelationshipsByClaimID :exec
DELETE FROM relationships WHERE from_claim_id = ? OR to_claim_id = ?
`

type DeleteRelationshipsByClaimIDParams struct {
	FromClaimID string `json:"from_claim_id"`
	ToClaimID   string `json:"to_claim_id"`
}

func (q *Queries) DeleteRelationshipsByClaimID(ctx context.Context, arg DeleteRelationshipsByClaimIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteRelationshipsByClaimID, arg.FromClaimID, arg.ToClaimID)
	return err
}

const listRelationshipsByClaim = `-- name: ListRelationshipsByClaim :many
SELECT id, type, from_claim_id, to_claim_id, created_at, created_by
FROM relationships
WHERE from_claim_id = ? OR to_claim_id = ?
ORDER BY created_at ASC
`

type ListRelationshipsByClaimParams struct {
	FromClaimID string `json:"from_claim_id"`
	ToClaimID   string `json:"to_claim_id"`
}

type ListRelationshipsByClaimRow struct {
	ID          string `json:"id"`
	Type        string `json:"type"`
	FromClaimID string `json:"from_claim_id"`
	ToClaimID   string `json:"to_claim_id"`
	CreatedAt   string `json:"created_at"`
	CreatedBy   string `json:"created_by"`
}

func (q *Queries) ListRelationshipsByClaim(ctx context.Context, arg ListRelationshipsByClaimParams) ([]ListRelationshipsByClaimRow, error) {
	rows, err := q.db.QueryContext(ctx, listRelationshipsByClaim, arg.FromClaimID, arg.ToClaimID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRelationshipsByClaimRow
	for rows.Next() {
		var i ListRelationshipsByClaimRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.FromClaimID,
			&i.ToClaimID,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRelationship = `-- name: UpsertRelationship :exec
INSERT INTO relationships (id, type, from_claim_id, to_claim_id, created_at, created_by)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(type, from_claim_id, to_claim_id) DO UPDATE SET
  created_at = excluded.created_at,
  created_by = excluded.created_by
`

type UpsertRelationshipParams struct {
	ID          string `json:"id"`
	Type        string `json:"type"`
	FromClaimID string `json:"from_claim_id"`
	ToClaimID   string `json:"to_claim_id"`
	CreatedAt   string `json:"created_at"`
	CreatedBy   string `json:"created_by"`
}

func (q *Queries) UpsertRelationship(ctx context.Context, arg UpsertRelationshipParams) error {
	_, err := q.db.ExecContext(ctx, upsertRelationship,
		arg.ID,
		arg.Type,
		arg.FromClaimID,
		arg.ToClaimID,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	return err
}
